http:
  routers:
    host-runner:
      rule: "PathPrefix(`/host-runner`)"
      middlewares:
        - "remove-host-runner-prefix"
      service: host-runner
  middlewares:
    remove-host-runner-prefix:
      replacePathRegex:
        regex: "^/host-runner/(.*)"
        replacement: "/$1"
  services:
    host-runner:
      loadBalancer:
        servers:
          - url: "http://localhost:5004"
