app = "sunodo-registry"
primary_region = "ord"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 5000
  force_https = true
 [http_service.concurrency]
   type = "requests"
   soft_limit = 200
   hard_limit = 250

[env]
  REGISTRY_HTTP_ADDR = ":5000"
  REGISTRY_HTTP_HOST = "https://registry.sunodo.io"
  # fly secrets set REGISTRY_HTTP_SECRET="$(openssl rand -base64 32)"
  # REGISTRY_HTTP_SECRET = ""
  REGISTRY_HTTP_DEBUG_ADDR = ":5001"
  REGISTRY_HTTP_DEBUG_PROMETHEUS_ENABLED = "true"
  REGISTRY_HTTP_DEBUG_PROMETHEUS_PATH = "/metrics"

  REGISTRY_STORAGE_CACHE_BLOBDESCRIPTOR = "inmemory"
  REGISTRY_STORAGE = "s3"
  REGISTRY_STORAGE_S3_REGION = "us-east-1"
  REGISTRY_STORAGE_S3_BUCKET = "sunodo-registry-dev"
  REGISTRY_STORAGE_S3_ENCRYPT = "false"
  REGISTRY_STORAGE_S3_SECURE = "true"
  REGISTRY_STORAGE_S3_V4AUTH = "true"
  REGISTRY_STORAGE_S3_CHUNKSIZE = 5242880
  # fly secrets set REGISTRY_STORAGE_S3_ACCESSKEY= REGISTRY_STORAGE_S3_SECRETKEY=
  # REGISTRY_STORAGE_S3_ACCESSKEY = ""
  # REGISTRY_STORAGE_S3_SECRETKEY = ""

  REGISTRY_AUTH_TOKEN_REALM = "https://api.sunodo.io/registry/token"
  REGISTRY_AUTH_TOKEN_SERVICE = "registry.sunodo.io"
  REGISTRY_AUTH_TOKEN_ISSUER = "api.sunodo.io"
  REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE = "/keys/registry.crt"

[metrics]
  port = 5001
  path = "/metrics"
