import { BaseCommand } from "../baseCommand.js";

export default class HashCommand extends BaseCommand<typeof HashCommand> {
    static summary = "Prints out image hash generated by the build command";

    static description =
        "Converts the binary generated by the build command to hexadecimal and prints out the result to console";

    public async run() {
        this.error(
            "Sunodo CLI is deprecated, please uninstall it and install Cartesi CLI",
        );
    }
}
