import chalk from "chalk";
import { Command, UsageError } from "clipanion";

import { SunodoCommand } from "../sunodoCommand.js";

export default class HashCommand extends SunodoCommand {
    static paths = [["hash"]];

    static usage = Command.Usage({
        description: "Prints out image hash generated by the build command",
        details:
            "Converts the binary generated by the build command to hexadecimal and prints out the result to console",
    });

    public async execute() {
        const hash = this.getMachineHash();
        if (hash) {
            if (!this.jsonEnabled) {
                this.context.stdout.write(
                    `${chalk.green("?")} Cartesi machine templateHash ${chalk.cyan(hash)}\n`,
                );
            } else {
                this.context.stdout.write(JSON.stringify({ hash }));
            }
        } else {
            throw new UsageError(
                "Cartesi machine snapshot not found, run 'sunodo build'",
            );
        }
    }
}
