http:
    routers:
        inspect_server:
            rule: "PathPrefix(`/inspect`)"
            service: inspect_server
    services:
        inspect_server:
            loadBalancer:
                servers:
                    - url: "http://validator:5005/inspect"
