version: "3.9"
services:
    dapp_deployer:
        command:
            [
                "create",
                "--rpc",
                "http://anvil:8545",
                "--deploymentFile",
                "/usr/share/sunodo/localhost.json",
                "--mnemonic",
                "test test test test test test test test test test test junk",
                # template hash is not relevant in host mode, so we can specify hash zero
                "--templateHash",
                "0x0000000000000000000000000000000000000000000000000000000000000000",
                "--outputFile",
                "/usr/share/sunodo/dapp.json",
            ]

    validator:
        environment:
            ENABLE_SUNODO_NODE: true
            # advance-runner
            SNAPSHOT_ENABLED: false
