version: "3.9"

services:
    validator:
        image: sunodo/rollups-node:0.6.1
        depends_on:
            dapp_deployer:
                condition: service_completed_successfully
        volumes:
            - blockchain-data:/usr/share/sunodo:ro
        healthcheck:
            test: ["CMD", "is_ready"]
            interval: 10s
            timeout: 1s
            retries: 5
        expose:
            - 4000
            - 5004
            - 5005
        env_file:
            - ${SUNODO_BIN_PATH}/node/default.env

    proxy:
        depends_on:
            validator:
                condition: service_healthy

    prompt:
        image: debian:bookworm-slim
        environment:
            PROMPT_TXT_01_ANVIL: "Anvil running at http://localhost:8545"
            PROMPT_TXT_02_GRAPHQL: "GraphQL running at http://localhost:8080/graphql"
            PROMPT_TXT_03_INSPECT: "Inspect running at http://localhost:8080/inspect/"
            PROMPT_TXT_04_EXPLORER: "Explorer running at http://localhost:8080/explorer/"
            PROMPT_TXT_10_EXIT: "Press Ctrl+C to stop the node"
        command:
            - /bin/bash
            - -c
            - |
                for txt_file in $${!PROMPT_TXT_*}
                do
                    declare -n txt_content=$$txt_file
                    _txt_file=$${txt_file:11}
                    echo "$$txt_content"
                done
                trap exit INT TERM; sleep infinity & wait
        working_dir: /prompt
        depends_on:
            proxy:
                condition: service_healthy

    traefik-config-generator:
        environment:
            TRAEFIK_CONFIG_INSPECT_SERVER: |
                http:
                    routers:
                        inspect_server:
                            rule: "PathPrefix(`/inspect`)"
                            service: inspect_server
                    services:
                        inspect_server:
                            loadBalancer:
                                servers:
                                    - url: "http://validator:5005/inspect"
            TRAEFIK_CONFIG_GRAPHQL_SERVER: |
                http:
                    routers:
                        graphql_server:
                            rule: "PathPrefix(`/graphql`)"
                            service: graphql_server
                    services:
                        graphql_server:
                            loadBalancer:
                                servers:
                                    - url: "http://validator:4000/graphql"

