http:
  routers:
    graphql_server:
      rule: "PathPrefix(`/graphql`)"
      service: graphql_server
  services:
    graphql_server:
      loadBalancer:
        servers:
          - url: "http://localhost:4000/graphql"
