log:
  level: WARN

accessLog: {}

entryPoints:
  web:
    address: ":8080"
  traefik:
    address: ":8088"

providers:
  file:
    directory: /etc/traefik/conf.d
    watch: true

metrics:
  prometheus:
    addServicesLabels: true
