name: anvil
on:
    workflow_call:
        secrets:
            DOCKERHUB_USERNAME:
                required: true
            DOCKERHUB_TOKEN:
                required: true
    pull_request:
        paths:
            - .github/workflows/anvil.yaml
            - packages/anvil/**
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
    cancel-in-progress: true
permissions:
    contents: read
    packages: write
    actions: write
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Get package tag/version
              id: package-version
              if: ${{ github.event_name == 'push' }}
              run: |
                  jq -r '"PACKAGE_VERSION=\(.version)"' packages/anvil/package.json >> "$GITHUB_OUTPUT"

            - name: Docker meta
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: |
                      docker.io/sunodo/anvil,enable=${{ github.event_name != 'pull_request' }}
                      ghcr.io/sunodo/anvil
                  tags: |
                      type=raw,value=${{ steps.package-version.outputs.PACKAGE_VERSION }},enable=${{ github.event_name == 'push' }}
                      type=ref,event=pr
                  labels: |
                      org.opencontainers.image.title=Sunodo anvil
                      org.opencontainers.image.description=Sunodo anvil image with healthcheck

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Login to DockerHub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push
              uses: docker/bake-action@v4
              with:
                  workdir: packages/anvil
                  files: |
                      ./docker-bake.hcl
                      ./docker-bake.platforms.hcl
                      ${{ steps.meta.outputs.bake-file }}
                  set: |
                      *.cache-from=type=gha
                      *.cache-to=type=gha,mode=max
                  push: true
