name: cartesi-node
on:
    push:
        branches:
            - main
        tags:
            - v*
    pull_request:
        paths:
            - .github/workflows/cartesi-node.yaml
            - packages/cartesi-node/**
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true
permissions:
    contents: read
    packages: write
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Docker meta
              id: meta
              uses: docker/metadata-action@v4
              with:
                  images: |
                      docker.io/sunodo/cartesi-node,enable=${{ github.event_name != 'pull_request' }}
                      ghcr.io/sunodo/cartesi-node
                  tags: |
                      type=semver,pattern={{version}}
                      type=edge
                      type=ref,event=pr
                  labels: |
                      org.opencontainers.image.title=Sunodo's cartesi-node
                      org.opencontainers.image.description=Sunodo's cartesi-node in a single container

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Login to DockerHub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push
              uses: docker/bake-action@v3
              with:
                  workdir: packages/cartesi-node
                  files: |
                      ./docker-bake.hcl
                      ${{ steps.meta.outputs.bake-file }}
                  set: |
                      *.cache-from=type=gha
                      *.cache-to=type=gha,mode=max
                  push: true
