name: machine-emulator-tools
on:
    push:
        branches:
            - main
        tags:
            - v*
    pull_request:
        paths:
            - .github/workflows/machine-emulator-tools.yaml
            - packages/machine-emulator-tools/**
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true
permissions:
    contents: read
    packages: write
    id-token: write
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Set up Docker Buildx
              id: buildx
              uses: docker/setup-buildx-action@v2
              with:
                  platforms: linux/riscv64

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Login to DockerHub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push
              uses: docker/bake-action@v3
              with:
                  workdir: packages/machine-emulator-tools
                  builder: ${{ steps.buildx.outputs.name }}
                  provenance: false
                  files: |
                      ./docker-bake.hcl
                  set: |
                      *.cache-from=type=gha
                      *.cache-to=type=gha,mode=max
                  push: true
