entryPoints:
    web:
        address: ":8080"
    traefik:
        address: ":8088"
ping: {}
providers:
    file:
        directory: /etc/traefik/conf.d
metrics:
    prometheus:
        addServicesLabels: true
